# Here, we will try to use numbers in the python

num1 = int(input("Please enter some number"))

print("Value of num1 is "+ str(num1))

# Reassigning the value of num1
num1 = int(input("Reassign the value to num1"))

print("Value of num1 is "+ str(num1))


# We can unassing the value given to num1 as follows
del num1

# Belwo line will give an error 'num1 is not defined'
# print("Value of num1 is "+num1)


# Converting the num1 into the floating point
num1_float = float(24)

print("Value of new_num1 is "+str(num1_float))


num1_long = int(num1_float)

# Below code is giving the error as 'long is not defined....'
# num1_long = long(num1_long)

print("Value of num1_long is "+str(num1_long))


# Finding the absolute value 
my_var1 = -125

print("The absolute value of my_var1 is "+str(abs(my_var1)))


# modf() function will give the fractional and integer part of the anything passed in it

import math

print("The value of math.modf(123.53553535) is:- ",math.modf(123.53553535))

my_num2 = float(input("Enter some float value number"))


# round will print the number with the number of values followed by decimal
print("The value of my_num2 is:- ",round(my_num2,3))


# Applying the random number.
# Random numbers are used for testing, security, games etc....
# choice will generate random numbers from list, tuples or string....


# choice is not directly available in python, so we need to import random 

import random
print("Random number generated by choice([2,3,4,11,12,13,23,24]) ", random.choice([2,3,4,11,12,13,23,24]))



# Another way of generating random number
print("Random number generated by randrange(10,1000,3) ",random.randrange(10,1000,3))



# Generation of random number between 0 to 1
print("Random number generated by random.random() ",random.random())



# seed is very useful to generate same number again when using some random method
random.seed(10)
print("Random number generated by random.random() ",random.random())


random.seed(10)
print("Random number generated by random.random() ",random.random()) 



my_list1 = [2,3,4,5,6,7,3,4,1]

# random.shuffle(my_list1) when printed will return 'none' but instead if we print the list after 
 # running the method random.shuffle(my_list1) then list will be shuffled....
random.shuffle(my_list1)
print("Shuffling the list my_list1 ",my_list1)
print()

random.shuffle(my_list1)
print("Shuffling the list my_list1 ",my_list1)


print()

# Generating the random number between x and y
print("Generating the random ",random.uniform(10,10000))
